- name: Copy and deploy docker_compose
  hosts: ubuntu
  tasks:
    - name: Copy .env file
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: ~/
        mode: 0700
      with_fileglob:
        - "../{{ inventory_hostname }}/.env*"
    - name: Copy docker-compose.yml
      ansible.builtin.copy:
        src: ../{{ inventory_hostname }}/docker-compose.yml
        dest: ~/docker-compose.yml
        follow: true
        mode: 0700
    - name: Run docker-compose up -d
      community.docker.docker_compose:
        project_src: .
        remove_orphans: true
    - name: Copy reverse proxy HTML file
      ansible.builtin.copy:
        src: ../public/swag.html
        dest: /var/appdata/swag/www/index.html
        mode: 0700
      when: "'venus' in inventory_hostname"
