- name: Copy and deploy docker_compose
  hosts: docker
  tasks:
    - name: Copy docker-compose.yml
      ansible.builtin.copy:
        src: ../docker-compose.yml
        dest: ~/docker-compose.yml
        mode: 0700
        follow: true
    - name: Run docker-compose up -d
      community.docker.docker_compose:
        project_src: .
      register: output
    - name: Print debugging information
      ansible.builtin.debug:
        var: output
