- name: Copy and deploy docker_compose (media)
  hosts: media
  tasks:
    - name: Copy placeholder html file
      ansible.builtin.copy:
        src: ../public/swag.html
        dest: /var/appdata/swag/www/index.html
        mode: 0700
    - name: Copy docker-compose.yml
      ansible.builtin.copy:
        src: ../media/docker-compose.yml
        dest: ~/docker-compose.yml
        mode: 0700
        follow: true
    - name: Run docker-compose up -d
      community.docker.docker_compose:
        project_src: .
        remove_orphans: true
      register: output
    - name: Print debugging information
      ansible.builtin.debug:
        var: output
