- name: Copy and deploy docker_compose (games)
  hosts: games
  tasks:
    - name: Copy docker-compose.yml
      ansible.builtin.copy:
        src: ../games/docker-compose.yml
        dest: ~/docker-compose.yml
        mode: 0700
        follow: true
    - name: Run docker-compose up -d
      community.docker.docker_compose:
        project_src: .
        remove_orphans: true
