---
# tasks file for factorio
- name: Create factorio directory
  ansible.builtin.file:
    path: /srv/docker/factorio
    state: directory
    owner: root
    group: docker
    mode: '0775'
- name: Create factorio container
  community.docker.docker_container:
    name: factorio
    image: factoriotools/factorio
    state: started
    restart_policy: always
    ports:
      - "34197:34197/udp"
    volumes:
      - /srv/docker/factorio:/factorio
- name: Copy factorio settings
  ansible.builtin.template:
    src: server-settings.json.j2
    dest: /srv/docker/factorio/config/server-settings.json
  notify: factorio::restart
- name: S Prometheus factorio_metrics
  ansible.builtin.import_tasks:
    name: factorio-metrics.yaml
  when: factorio_metrics
