version: "3.9"
services:
  direwolf:
    image: itzg/minecraft-server
    container_name: direwolf
    ports:
      - 25565:25565
    environment:
      - EULA=TRUE
      - TYPE=FTBA
      - FTB_MODPACK_ID=101
      - FTB_MODPACK_VERSION_ID=2342
      - MEMORY=8G
    volumes:
      - /var/appdata/minecraft/server/direwolf:/data
    restart: unless-stopped
  direwolf-backup:
    image: itzg/mc-backup
    container_name: direwolf-backup
    environment:
      - BACKUP_METHOD=restic
      - INITIAL_DELAY=5m
      - RESTIC_PASSWORD=direwolf
      - RESTIC_REPOSITORY=/backups
      - BACKUP_INTERVAL=1h
      - RCON_HOST=direwolf
    volumes:
      - /var/appdata/minecraft/server/direwolf:/data:ro
      - /var/appdata/minecraft/backup/direwolf:/backups
    depends_on:
      - direwolf
    restart: unless-stopped
networks:
  default:
    name: games
