version: "3.9"
services:
  # direwolf:
  #   image: itzg/minecraft-server
  #   container_name: direwolf
  #   ports:
  #     - 25565:25565
  #   environment:
  #     - EULA=TRUE
  #     - TYPE=FTBA
  #     - FTB_MODPACK_ID=101
  #     - FTB_MODPACK_VERSION_ID=2342
  #     - MEMORY=8G
  #   volumes:
  #     - /var/appdata/minecraft/server/direwolf:/data
  #   restart: unless-stopped
  # direwolf-backup:
  #   image: itzg/mc-backup
  #   container_name: direwolf-backup
  #   environment:
  #     - BACKUP_METHOD=restic
  #     - INITIAL_DELAY=5m
  #     - RESTIC_PASSWORD=direwolf
  #     - RESTIC_REPOSITORY=/backups
  #     - BACKUP_INTERVAL=1h
  #     - RCON_HOST=direwolf
  #   volumes:
  #     - /var/appdata/minecraft/server/direwolf:/data:ro
  #     - /var/appdata/minecraft/backup/direwolf:/backups
  #   depends_on:
  #     - direwolf
  #   restart: unless-stopped
  proxy:
    image: itzg/bungeecord
    container_name: proxy
    ports:
      - 25570:25577
    volumes:
      - /var/appdata/minecraft/server/proxy:/server
    environment:
      - TYPE=VELOCITY
      - ENABLE_RCON=TRUE
  survival:
    image: itzg/minecraft-server
    container_name: survival
    volumes:
      - /var/appdata/minecraft/server/survival:/data
    environment:
      - TYPE=PAPER
      - EULA=true
      - ONLINE_MODE=false
      - MEMORY=8G
      - USE_AIKAR_FLAGS=true
      - VERSION=1.19.3
    ports:
      - 8123:8123 # dynmap
  survival-backup:
    image: itzg/mc-backup
    container_name: survival-backup
    environment:
      - BACKUP_METHOD=restic
      - INITIAL_DELAY=5m
      - RESTIC_PASSWORD=survival
      - RESTIC_REPOSITORY=/backups
      - BACKUP_INTERVAL=1h
      - RCON_HOST=survival
    volumes:
      - /var/appdata/minecraft/server/survival:/data:ro
      - /var/appdata/minecraft/backup/survival:/backups
    depends_on:
      - survival
    restart: unless-stopped
  creative:
    image: itzg/minecraft-server
    container_name: creative
    volumes:
      - /var/appdata/minecraft/server/creative:/data
    environment:
      - TYPE=PAPER
      - EULA=true
      - ONLINE_MODE=false
      - MEMORY=4G
      - USE_AIKAR_FLAGS=true
      - VERSION=1.19.3
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=minecraft #optional
      - MYSQL_USER=minecraft #optional
      - MYSQL_PASSWORD=thenether #optional
    volumes:
      - /var/appdata/mariadb:/config 
    ports:
      - 3306:3306
networks:
  default:
    name: games
