version: "3.9"
services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=chrisnethercott.co.uk
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=route53
      - EMAIL=ccnethercott@gmail.com
    volumes:
      - /home/christopher/homelab/appdata/swag:/config
    ports:
      - 443:443
      - 80:80
    restart: always
