version: "3.9"
services:
  factorio:
    image: factoriotools/factorio
    container_name: factorio
    ports:
     - "34197:34197/udp"
    volumes:
     - /opt/factorio:/factorio
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=chrisnethercott.co.uk
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=route53
      - EMAIL=ccnethercott@gmail.com
    volumes:
      - /var/appdata/swag:/config
    ports:
      - 443:443
      - 80:80
    restart: always
  paperless:
    image: lscr.io/linuxserver/paperless-ng
    container_name: paperless
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PAPERLESS_AUTO_LOGIN_USERNAME=christopher
    volumes:
      - /var/appdata/paperless:/config
      - /var/paperless:/data
    restart: unless-stopped
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - /var/appdata/homer:/www/assets
    environment:
      - UID=1000
      - GID=1000
  nzbget:
    image: lscr.io/linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /var/appdata/nzbget:/config
      - /var/downloads:/downloads
    restart: unless-stopped
  nzbhydra2:
    image: lscr.io/linuxserver/nzbhydra2
    container_name: nzbhydra2
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /var/appdata/nzbhydra2:/config
      - /var/downloads:/downloads
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /var/appdata/sonarr:/config
      - /var/media/TV:/tv
      - /var/downloads:/downloads
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /var/appdata/radarr:/config
      - /var/media/Film:/movies
      - /var/downloads:/downloads
    restart: unless-stopped
networks:
  default:
    name: lsio