version: "3.9"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  factorio:
    image: factoriotools/factorio
    container_name: factorio
    ports:
     - "34197:34197/udp"
    volumes:
     - /opt/factorio:/factorio
  mariadb:
    image: lscr.io/linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=my_root_passwd
    volumes:
      - /var/appdata/mariadb:/config
    ports:
      - 3306:3306
    restart: always
  phpmyadmin:
    image: lscr.io/linuxserver/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PMA_HOSTS=mariadb
      - PMA_ABSOLUTE_URI=https://phpmyadmin.chrisnethercott.co.uk
    volumes:
      - /var/appdata/phpmyadmin:/config
    restart: unless-stopped
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=chrisnethercott.co.uk
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=route53
      - EMAIL=ccnethercott@gmail.com
    volumes:
      - /var/appdata/swag:/config
    ports:
      - 443:443
      - 80:80
    restart: always
  authelia:
    image: authelia/authelia:4.21.0
    container_name: authelia
    environment:
      - TZ=Europe/London
    volumes:
      - /var/appdata/authelia:/config
    restart: unless-stopped
  paperless:
    image: lscr.io/linuxserver/paperless-ng
    container_name: paperless
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PAPERLESS_AUTO_LOGIN_USERNAME=christopher
    volumes:
      - /var/appdata/paperless:/config
      - /var/paperless:/data
    restart: unless-stopped
  nzbget:
    image: lscr.io/linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /var/appdata/nzbget:/config
      - /var/downloads:/downloads
    restart: unless-stopped
  nzbhydra2:
    image: lscr.io/linuxserver/nzbhydra2
    container_name: nzbhydra2
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /var/appdata/nzbhydra2:/config
      - /var/downloads:/downloads
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /var/appdata/sonarr:/config
      - /var/media/TV:/tv
      - /var/downloads:/downloads
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /var/appdata/radarr:/config
      - /var/media/Film:/film
      - /var/downloads:/downloads
    restart: unless-stopped
  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /var/appdata/lidarr:/config
      - /var/media/Music:/music
      - /var/downloads:/downloads
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8080
    volumes:
      - /var/appdata/qbittorrent:/config
      - /var/torrent:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  nextcloud:
    image: lscr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /var/appdata/nextcloud:/config
      - /var/appdata/nextcloud-data:/data
    restart: unless-stopped
  tautulli:
    image: lscr.io/linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /var/appdata/tautulli:/config
    restart: unless-stopped
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    environment:
      - TYPE=PAPER
      - EULA=true
      - MEMORY=8G
      # EssentialsX, Vault, LuckPerms, CoreProtect, OnePlayerSleep, Tree Assist
    ports:
      - 25565:25565
    volumes:
      - /var/appdata/minecraft:/data
    restart: unless-stopped
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /var/appdata/heimdall:/config
    restart: unless-stopped
networks:
  default:
    name: lsio
