- name: Homelab CI / CD
  hosts: all
  vars:
    ansible_become_password: "{{ users['ansible'] | eyaml }}"
  tasks:
    - name: Install host roles dynamically based on variables
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop: "{{ host_roles }}"
      when: host_roles is defined
