- name: Homelab CI / CD
  hosts: all
  vars:
    ansible_become_password: "{{ users['ansible'] | eyaml }}"
  tasks:
    - name: Update packages
      become: true
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
        autoremove: true
        autoclean: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'
    - name: Install Docker on hosts
      ansible.builtin.include_role:
        name: geerlingguy.docker
      vars:
        docker_users: "{{ users }}"
        docker_install_compose: true
      when: enable_docker
    