[web]
web.nethercott.co.uk ansible_user=root

[media]
media.chrisnethercott.co.uk ansible_user=christopher

[home]
home.chrisnethercott.co.uk ansible_user=christopher

[snapclient]
kitchen
office
living-room
bedroom

[snapclient:vars]
ansible_user=christopher
