---
# tasks file for caddy
- name: Include caddy role
  ansible.builtin.include_role:
    name: caddy_ansible.caddy_ansible
    public: true
  vars:
    # noqa: var-naming[no-role-prefix]
    caddy_config: |
      {
          email ccnethercott@gmail.com
      }

      *.chrisnethercott.co.uk {
          tls {
            dns cloudflare {{ caddy_cloudflare_token }}
          }
          root * /var/www/fallback
          file_server
      }
    caddy_packages:
      - github.com/caddy-dns/cloudflare

- name: Create Caddy sites directory
  ansible.builtin.file:
    name: /etc/caddy/sites
    state: directory
    owner: "{{ caddy_user }}"
    mode: "0755"

- name: Create Caddy fallback directory
  ansible.builtin.file:
    name: /var/www/fallback
    state: directory
    owner: "{{ caddy_user }}"
    mode: "0755"

- name: Copy Caddy fallback page
  ansible.builtin.copy:
    src: fallback/index.html
    dest: /var/www/fallback/index.html
    owner: "{{ caddy_user }}"
    mode: "0644"

- name: Copy custom Caddy config
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ caddy_user }}"
    mode: "0644"
  loop:
    - { src: authelia.caddy.j2, dest: /etc/caddy/authelia.caddy }
    - { src: proxy.caddy.j2, dest: /etc/caddy/proxy.caddy }
