---
# tasks file for caddy
- name: Create caddy directory
  become: true
  ansible.builtin.file:
    path: /srv/docker/caddy
    state: directory
    owner: root
    group: docker
    mode: '0775'
- name: Create Caddyfile
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /srv/docker/caddy/Caddyfile
  notify: caddy::restart
- name: Create /var/www/html directory
  become: true
  ansible.builtin.file:
    path: /var/www/html
    state: directory
    owner: root
    group: docker
    mode: '0775'
- name: Create index.html
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: caddy::restart
- name: Create caddy container
  community.docker.docker_container:
    name: caddy
    image: caddy
    state: started
    restart_policy: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /srv/docker/caddy:/data
      - /srv/docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /var/www/html:/var/www/html
  notify: caddy::restart
