- name: Create Ping config file
  ansible.builtin.template:
    src: ping.yml.j2
    dest: /etc/prometheus/ping.yml

- name: Run Ping exporter
  community.docker.docker_container:
    name: prometheus_ping
    image: docker.io/czerwonk/ping_exporter
    pull: true
    restart_policy: always
    networks:
      - name: prometheus_priv
        aliases: ping
    volumes:
      - "/etc/prometheus/ping.yml:/config/config.yml:ro"
    ports:
      - 9427:9427
