- name: Create public HTTP Docker network
  community.docker.docker_network:
    name: public_http
    state: present

- name: Create private PostgreSQL Docker network
  community.docker.docker_network:
    name: postgresql
    state: present

- name: Run Watchtower
  community.docker.docker_container:
    name: watchtower
    image: containrrr/watchtower
    container_name: watchtower
    pull: true
    restart_policy: always
