---
users:
  christopher: ENC[PKCS7,MIIBiQYJKoZIhvcNAQcDoIIBejCCAXYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAmKDGv+IM2uPIKIesYVg40zNLwbBhwch47yYmg2uqlS0z6ZYmrXuWI2E5IERLMtRXrudoii0i2NF7h0FsZ4OHpcVZ3EA8XMKn9/99INrl0p/VzNO3SZee/bmK+QoBqD/h1MyubFB8vl34EmLrRWGWvZW74HtBD0zju4qcbM5Z9Kjg9RxDTZ0BQXk/m3PJU1qsyKKAjpESW68i9W3W52IbCzzcCe9WtkzAKQdO/q0vsS+EY5p9TqPZ9RFQRBqR5cbwygaFB0ScGMmpK4lSd6lY0grFoFeVqnibJ7SWl0o7ZM6hPkj84Y/Hnd4fTwGU4KOulhw8RLdl6OPasSoq0gOGNzBMBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBA/vn3ool1aQTOz4lqKngJEgCCVXUSMO8Y1cG/nAAouYbkim8suVrfZrS8tCd2soAccow==] 

enable_docker: true

host_roles:
  - factorio

# Factorio bits and bobs
factorio_server_name: "Erebor"
factorio_server_description: "The Lonely Mountain. A free server for all to play on"
factorio_server_tags:
  - "public"
  - "pve"
  - "dedicated"

factorio_username: "Thorin17"
factorio_token: ENC[PKCS7,MIIBiQYJKoZIhvcNAQcDoIIBejCCAXYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAQ9GmGLcctbGjX/wE4UwwBfd7y2dj8KWZDSX/lgMYxwAh2TaLtFfvY/7KbZbq1ywHZ2NVxrvpDTo2Wk9Yrq7hi7wS0E1HkgqMwvP/K2TaoHXTlLkJm/jvkxNUz0At30tEHSa3yjKecbxnOudc/Dd65R/N+u8TviFRQ1RmsoZiKtcY603nC/JdBLGe5gfWQzk3eHDHz9LuIUScwZKdcqIMUPUVLITXddUbUuyngrdhTI59Fd5/UdUr+FmRHbqQrRTfcdyCJ1R3BfMuMwudjsIHiElP7eKF/WWzvHSlwnHTRKmnuq8XpuXFJu72HfSGf+VyXRwg0WJyspiNX+iNJFLr9zBMBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBB3PTwAEQDgkavBfL58lTWQgCDl9O50U8o1CeMv+hh+HRlCF5gWRVH25r1iH86pD7zQEQ==]
factorio_metrics: true

factorio_admins:
  - "Thorin17"
