- name: Setup paperless-ngx
  hosts: paperless
  pre_tasks:
    - name: Perform apt update and upgrade
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'
    - name: Install psycopg2
      become: true
      ansible.builtin.apt:
        name: "python{{ (ansible_python.version.major == 3) | ternary('3', '') }}-psycopg2"
    - name: Install postgresql
      ansible.builtin.include_role:
        name: galaxyproject.postgresql
        apply:
          become: true
      vars:
        postgresql_flavor: pgdg
        postgresql_version: 16
        postgresql_conf:
          - port: "{{ paperless_ngx_conf_dbport }}"
          - listen_addresses: "'{{ paperless_ngx_conf_dbhost }}'"
    - name: Create postgresql user and db
      ansible.builtin.include_role:
        name: galaxyproject.postgresql_objects
        apply:
          become: true
          become_user: postgres
      vars:
        postgresql_objects_users:
          - name: "{{ paperless_ngx_conf_dbuser }}"
            password: "{{ paperless_ngx_conf_dbpass }}"
        postgresql_objects_databases:
          - name: "{{ paperless_ngx_conf_dbname }}"
            owner: "{{ paperless_ngx_conf_dbuser }}"
  roles:
    - paperless_ngx.paperless_ngx
    - role: caddy_ansible.caddy_ansible
      tags: caddy
  post_tasks:
    - name: Only allow HTTP/HTTPs, SSH, and ICMP
      ansible.builtin.ufw:
        rule: allow
        port: "{{ item }}"
        proto: "{{ item == 'ssh' | ternary('tcp', 'both') }}"
      with_items:
        - http
        - https
        - ssh
        - icmp
