- name: Initial setup script
  hosts: all
  pre_tasks:
    - name: Perform apt update and upgrade
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'
  roles:
    - geerlingguy.security
    - geerlingguy.ntp
  post_tasks:
    - name: Check if /var/run/reboot-required exists
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required
    - name: Reboot if /var/run/reboot-required exists
      ansible.builtin.reboot:
      when: reboot_required.stat.exists
