- name: Install zsh with antigen plugin manager
  hosts: homelab
  become: true
  roles:
    - role: gantsign.antigen
      users:
        - username: christopher
          antigen_libraries:
            - name: oh-my-zsh
          antigen_theme:
            name: robbyrussell
          antigen_bundles:
            - name: git
            - name: pip
            - name: zsh-syntax-highlighting
              url: zsh-users/zsh-syntax-highlighting
            - name: zsh-autosuggestions
              url: zsh-users/zsh-autosuggestion
