name: Deploy Docker
on:
  push:
    branches:
      - "main"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-actions@v1
        with:
          authkey: ${{ secrets.TAILSCALE_KEY }}
      - name: Deploy Docker Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbook/deploy-docker.yml
